DROP TABLE IF EXISTS Config;
CREATE TABLE IF NOT EXISTS Config (Id INTEGER PRIMARY KEY, Name TEXT, Value TEXT);

DROP TABLE IF EXISTS Cache;
CREATE TABLE IF NOT EXISTS Cache (Id INTEGER PRIMARY KEY, Name TEXT, Value TEXT);

DROP TABLE IF EXISTS Queue;
CREATE TABLE IF NOT EXISTS Queue (Id INTEGER PRIMARY KEY, UserId TEXT, Action TEXT, Value TEXT, Response TEXT, Status TEXT);

DROP TABLE IF EXISTS Session;
CREATE TABLE IF NOT EXISTS Session (Id INTEGER PRIMARY KEY, UserId TEXT, Value TEXT, ExpiresAt INTEGER);
