DROP TABLE IF EXISTS Config;
CREATE TABLE IF NOT EXISTS Config (id INTEGER PRIMARY KEY, name TEXT, value TEXT);

DROP TABLE IF EXISTS Cache;
CREATE TABLE IF NOT EXISTS Cache (id INTEGER PRIMARY KEY, name TEXT, value TEXT);

DROP TABLE IF EXISTS Session;
CREATE TABLE IF NOT EXISTS Session (id INTEGER PRIMARY KEY, userId TEXT, value TEXT, expiresAt INTEGER);
