name = "sheet-db"
main = "src/index.tsx"
compatibility_date = "2024-10-01"

[vars]
ENVIRONMENT = "development"
ENCRYPTION_KEY = "dev-encryption-key-replace-in-production-32chars"
OAUTH_STATE_SECRET = "dev-oauth-state-secret-replace-in-production-32chars"

# D1 Database binding for development environment
[[d1_databases]]
binding = "DB"
database_name = "sheet-db-dev"
database_id = "98df6d81-b92f-4cd8-a2a9-7dd7c63c3aa2"
migrations_dir = "src/db/migrations"

# Production environment configuration
[env.production]
name = "sheet-db-production"
vars = { ENVIRONMENT = "production" }

# D1 Database binding for production environment
[[env.production.d1_databases]]
binding = "DB"
database_name = "sheet-db-production"
database_id = "9a6f7aaa-c7dd-401b-9946-a443a6ba647f"
migrations_dir = "src/db/migrations"
