name = "sheet-db"
main = "src/index.tsx"
compatibility_date = "2024-10-01"

[vars]
ENVIRONMENT = "development"

# D1 Database binding for development environment
[[d1_databases]]
binding = "DB"
database_name = "sheet-db-dev"
database_id = "98df6d81-b92f-4cd8-a2a9-7dd7c63c3aa2"
migrations_dir = "src/db/migrations"

# Production environment configuration
[env.production]
name = "sheet-db-production"
vars = { ENVIRONMENT = "production" }

# D1 Database binding for production environment
[[env.production.d1_databases]]
binding = "DB"
database_name = "sheet-db"
database_id = "250f9762-08d9-4d28-9739-30e8b0076921"
migrations_dir = "src/db/migrations"
