openapi: 3.0.3
info:
  title: SheetDB Local Development Utilities
  version: 1.0.0
  description: Local-only endpoints for smoke checks, parity checks, and reset operations.
servers:
  - url: http://localhost:8787
paths:
  /_local/smoke-check:
    post:
      summary: Run a local smoke check
      responses:
        "200":
          description: Smoke check completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SmokeCheckResult"
  /_local/parity:
    get:
      summary: Get parity checklist status
      responses:
        "200":
          description: Parity checklist results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParityChecklist"
  /_local/reset:
    post:
      summary: Reset local data to baseline
      responses:
        "200":
          description: Reset completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResetResult"
components:
  schemas:
    SmokeCheckResult:
      type: object
      required:
        - readStatus
        - writeStatus
      properties:
        readStatus:
          type: string
          enum: [pass, fail]
        writeStatus:
          type: string
          enum: [pass, fail]
        details:
          type: string
    ParityChecklist:
      type: object
      required:
        - constraints
      properties:
        constraints:
          type: array
          items:
            $ref: "#/components/schemas/ParityConstraint"
    ParityConstraint:
      type: object
      required:
        - name
        - status
      properties:
        name:
          type: string
        status:
          type: string
          enum: [pass, fail, unknown, required]
        remediation:
          type: string
    ResetResult:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [pass, fail]
        details:
          type: string
